# Generated by Django 3.0.2 on 2020-02-09 10:43

from django.db import migrations, models
import django.db.models.deletion
import monthyear.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('residential_status', models.CharField(choices=[('R', 'Resident'), ('NR', 'Non-Resident')], max_length=2, null=True)),
                ('national_id', models.CharField(max_length=10, null=True, unique=True)),
                ('kra_pin', models.CharField(max_length=11, null=True, unique=True)),
                ('nssf_no', models.CharField(max_length=15, null=True, unique=True)),
                ('nhif_no', models.CharField(max_length=15, null=True, unique=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('basic_salary', models.CharField(max_length=15, null=True)),
                ('bank', models.CharField(max_length=50, null=True)),
                ('bank_account_name', models.CharField(max_length=255, null=True)),
                ('bank_account_number', models.CharField(max_length=35, null=True)),
                ('bank_branch', models.CharField(max_length=40, null=True)),
                ('employee_personal_number', models.CharField(max_length=50, null=True)),
                ('date_of_employment', models.DateField(null=True)),
                ('contract_type', models.CharField(choices=[('P', 'Permanent'), ('T', 'Temporary')], max_length=1, null=True)),
                ('job_title', models.CharField(max_length=50, null=True)),
                ('employee_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('mobile_phone', models.CharField(max_length=15, null=True)),
                ('allowances', models.ManyToManyField(blank=True, to='payroll.Allowance')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', monthyear.models.MonthField(help_text='some help...', null=True, verbose_name='Month Value')),
                ('gross_pay', models.IntegerField(null=True)),
                ('nssf_deduction', models.IntegerField(null=True)),
                ('nhif_deduction', models.IntegerField(null=True)),
                ('payee', models.IntegerField(null=True)),
                ('personal_relief', models.IntegerField(null=True)),
                ('total_tax', models.IntegerField(null=True)),
                ('net_salary', models.IntegerField(null=True)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeModel')),
            ],
        ),
    ]
