# Generated by Django 3.0.2 on 2020-01-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('residential_status', models.CharField(choices=[('R', 'Resident'), ('NR', 'Non-Resident')], max_length=2)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('kra_pin', models.CharField(max_length=11, unique=True)),
                ('nssf_no', models.CharField(max_length=15, unique=True)),
                ('nhif_no', models.CharField(max_length=15, unique=True)),
                ('passport_photo', models.ImageField(blank=True, upload_to='')),
                ('basic_salary', models.CharField(max_length=15)),
                ('bank_account_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=35)),
                ('bank_branch', models.CharField(max_length=40)),
            ],
        ),
    ]
