# Generated by Django 3.0.2 on 2020-01-07 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20200107_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollmodel',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeModel'),
        ),
        migrations.AddField(
            model_name='payrollmodel',
            name='gross_pay',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payrollmodel',
            name='net_salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payrollmodel',
            name='nhif_deduction',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payrollmodel',
            name='nssf_deduction',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payrollmodel',
            name='payee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payrollmodel',
            name='personal_relief',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payrollmodel',
            name='total_tax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payrollmodel',
            name='month',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
