# Generated by Django 3.0.2 on 2020-01-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20200107_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='bank',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
