# Generated by Django 3.0.2 on 2020-01-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_employeemodel_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='contract_end_date',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='contract_type',
            field=models.CharField(choices=[('P', 'Permanent'), ('T', 'Temporary')], max_length=1, null=True),
        ),
    ]
