# Generated by Django 3.0.2 on 2020-01-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20200113_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='employee_job_number',
            new_name='employee_personal_number',
        ),
    ]
