# Generated by Django 3.0.2 on 2020-01-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20200113_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='allowances',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='allowances',
            field=models.ManyToManyField(null=True, to='payroll.Allowance'),
        ),
    ]
