# Generated by Django 3.0.2 on 2020-01-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_auto_20200113_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='allowances',
            field=models.ManyToManyField(blank=True, null=True, to='payroll.Allowance'),
        ),
    ]
