# Generated by Django 3.0.2 on 2020-01-14 09:04

from django.db import migrations, models
import monthyear.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_auto_20200113_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollmodel',
            name='monthyear',
        ),
        migrations.AddField(
            model_name='payrollmodel',
            name='month_year',
            field=monthyear.models.MonthField(null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='allowances',
            field=models.ManyToManyField(blank=True, to='payroll.Allowance'),
        ),
    ]
