# Generated by Django 3.0.2 on 2020-01-22 15:09

from django.db import migrations
import monthyear.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_auto_20200114_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollmodel',
            name='month_year',
            field=monthyear.models.MonthField(help_text='some help...', null=True, verbose_name='Month Value'),
        ),
    ]
